{% set name = "fairchem-core" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fairchem_core-{{ version }}.tar.gz
  sha256: 0c92ba218dc6fe52697a9d8e548fc5d3402a11c39c5e676ac80327c255391c6a

build:
  entry_points:
    - fairchem = fairchem.core._cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=24
    - pip
  run:
    - torchtnt
    - hydra-core
    - lmdb
    - python >={{ python_min }},<3.13
    - pytorch >=2.4.0,<2.5.dev0
    - numpy >=1.26.0,<2.0.0
    - python-lmdb
    - ase
    - pymatgen >=2023.10.3
    - pytorch_geometric
    - pytorch_scatter
    - pyyaml
    - tensorboard
    - wandb
    - numba
    - e3nn >=0.5
    - requests
    - orjson
    - tqdm
    - submitit

test:
  requires:
    - python {{ python_min }}
  imports:
    - fairchem.core
  commands:
    - fairchem --help

about:
  home: https://github.com/FAIR-Chem/fairchem
  summary: Machine learning models for use in catalysis as part of the Open Catalyst Project
  license: MIT
  license_file: src/fairchem/core/LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
