{% set name = "fairchem-core" %}
{% set version = "2.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/fairchem/archive/fairchem_core-{{ version }}.tar.gz
  sha256: 26f95694fea6899b9961b7ca47a4daeee9298525e25e0d2e71ca110f50075a24

build:
  entry_points:
    - fairchem = fairchem.core._cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install ./packages/fairchem-core -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=24
    - pip
  run:
    - ase-db-backends >=0.10.0
    - torch-geometric
    - huggingface_hub >=0.27.1
    - pydantic >=2.10.0
    - torchtnt
    - hydra-core
    - lmdb
    - python >={{ python_min }},<3.13
    - pytorch >=2.6.0,<2.7.dev0
    - numpy >=2.0,<2.3
    - python-lmdb
    - ase >=3.25.0
    - pymatgen >=2023.10.3
    - pytorch_geometric
    - pytorch_scatter
    - pyyaml
    - tensorboard
    - wandb
    - numba >=0.61.2
    - e3nn >=0.5
    - requests
    - orjson
    - tqdm
    - submitit

test:
  requires:
    - python {{ python_min }}
  imports:
    - fairchem.core
  commands:
    - fairchem --help

about:
  home: https://github.com/FAIR-Chem/fairchem
  summary: Machine learning models for use in catalysis as part of the Open Catalyst Project
  license: MIT
  license_file: src/fairchem/core/LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
