{% set name = "fairchem-core" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fairchem_core-{{ version }}.tar.gz
  sha256: ec088258065aa6c6cb6a00c3b6edcf95ce023e7d12d0bd09a280329b8cf4fa7a

build:
  entry_points:
    - fairchem = fairchem.core._cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=24
    - pip
  run:
    - torch-geometric
    - huggingface_hub >=0.27.1
    - pydantic >=2.10.0
    - torchtnt
    - hydra-core
    - lmdb
    - python >={{ python_min }},<3.13
    - pytorch >=2.4.0,<2.5.dev0
    - numpy >=1.26.0,<2.0.0
    - python-lmdb
    - ase
    - pymatgen >=2023.10.3
    - pytorch_geometric
    - pytorch_scatter
    - pyyaml
    - tensorboard
    - wandb
    - numba
    - e3nn >=0.5
    - requests
    - orjson
    - tqdm
    - submitit

test:
  requires:
    - python {{ python_min }}
  imports:
    - fairchem.core
  commands:
    - fairchem --help

about:
  home: https://github.com/FAIR-Chem/fairchem
  summary: Machine learning models for use in catalysis as part of the Open Catalyst Project
  license: MIT
  license_file: src/fairchem/core/LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
